title:               Rohit Gupta
url:                 rohitgupta.in
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Rohit Gupta
  url:               https://www.linkedin.com/in/rohitgupta61/
  email:             rohit.x.gupta@iiml.org

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
